### PR TITLE
Inital 1.3 update

### PR DESCRIPTION
**Pull request by Ogliss**
Hope its OK, but i did a quick update for 1.3

main changes were the transpiler for the quickstart button and a tweak to the upload logs function

### CODE REVIEW

**Comment by UnlimitedHugs** [comment]
Hey, saw the PR too late, as I already fixed things on my end.
I appreciate the effort, though.

**Comment by Ogliss** [comment]
No a bother, glad to see your back! i will pull the version i have on steam, hope no inconcinence was caused!

**Comment by Ogliss** [comment]
unlisted both Hugslib and Allow Tool, again hope i havent caused you any hasstle!

**Comment by UnlimitedHugs** [comment]
Oh, your username did look familiar. Thank you for publishing your builds in the meantime!
My release might come a bit later, though, as I'm taking care of some outstanding fixes.

**Comment by Ogliss** [comment]
Not a bother!, its too useful a tool!, alrighty, will leave mine as they are(unlisted) and delete em when you push the update then?

**Pull request closed without merging**
